
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StoreProvider from "../StoreProvider";
import TopNav from "../components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>
      {/* TopNav */}
      <TopNav />
      <div className="flex min-h-screen bg-gray-100 font-sans">

        {/* Sidebar */}
        <aside className="w-64 bg-white p-6 border-r">
          <div className="flex items-center mb-6">
            <div className="w-10 h-10 bg-red-500 rounded-full mr-3"></div>
            <h2 className="text-lg font-semibold">Udayanga Lakmal</h2>
          </div>
          <nav className="space-y-4">
            <a href="#" className="block text-gray-700 hover:text-green-600">Friends</a>
            <a href="#" className="block text-gray-700 hover:text-green-600">Celebrations</a>
            <a href="#" className="block text-gray-700 hover:text-green-600">Events</a>
            <a href="#" className="block text-gray-700 hover:text-green-600">My Wallet</a>
            <a href="#" className="block text-gray-700 hover:text-green-600">Surveys</a>
            <a href="#" className="block text-gray-700 hover:text-green-600">See More</a>
          </nav>
          <div className="mt-8">
            <h3 className="text-sm font-semibold text-gray-500 mb-2">Your Shortcuts</h3>
            <div className="space-y-2">
              <div className="flex items-center space-x-2 text-sm">
                <span className="bg-gray-200 text-gray-800 rounded px-2 py-1">RF</span>
                <span>RCB Fanclub</span>
              </div>
              <div className="flex items-center space-x-2 text-sm">
                <span className="bg-green-200 text-gray-800 rounded px-2 py-1">TC</span>
                <span>New born babies</span>
              </div>
            </div>
          </div>
        </aside>

        {/* Main content */}
        <main className="flex-1 p-6">
          {/* Post box */}
          <div className="bg-white p-4 rounded-lg shadow mb-4">
            <input
              type="text"
              placeholder="Eric, Let's cheer someone up today!"
              className="w-full p-2 border rounded mb-2"
            />
            <div className="flex space-x-4">
              <button className="text-yellow-600">🏆 Nominate</button>
              <button className="text-orange-600">🎖 Award</button>
              <button className="text-blue-600">📣 Announce</button>
            </div>
          </div>

          {/* Stories */}
          <div className="bg-white p-4 rounded-lg shadow mb-4">
            <h2 className="text-lg font-semibold mb-3">Stories</h2>
            <div className="flex space-x-4 overflow-x-auto">
              <div className="w-24 h-40 bg-gray-200 flex items-center justify-center rounded-lg">
                Create
              </div>
              {[...Array(3)].map((_, i) => (
                <div
                  key={i}
                  className="w-24 h-40 rounded-lg bg-cover bg-center"
                  style={{ backgroundImage: `url('https://via.placeholder.com/80x120')` }}
                ></div>
              ))}
            </div>
          </div>

          <StoreProvider>{children}</StoreProvider>
        </main>

        {/* Right sidebar */}
        <aside className="w-64 p-6 space-y-4">
          <div className="bg-white p-4 rounded-lg shadow">
            <h2 className="font-semibold mb-2">My Wallet</h2>
            <p className="text-lg font-bold">200</p>
            <button className="mt-2 px-4 py-1 bg-green-500 text-white rounded">
              Redeem Points
            </button>
          </div>

          <div className="bg-white p-4 rounded-lg shadow">
            <h2 className="font-semibold mb-2">Upcoming Celebrations</h2>
            <p>Anushka Sharma</p>
            <p className="text-sm text-gray-500">
              5 years anniversary in 3 days
            </p>
          </div>

          <div className="bg-white p-4 rounded-lg shadow">
            <h2 className="font-semibold mb-2">This Month Highlights</h2>
            <ul className="text-sm space-y-1">
              <li>
                Anushka Sharma - Anniversary,{' '}
                <span className="text-green-600">June 10</span>
              </li>
              <li>
                Alex Bernard - Birthday,{' '}
                <span className="text-green-600">June 10</span>
              </li>
              <li>
                Stephanie Jenson - Graduation,{' '}
                <span className="text-green-600">June 15</span>
              </li>
              <li>
                Jerad Osman - Farewell,{' '}
                <span className="text-green-600">June 20</span>
              </li>
              <li>
                Stephanie Jenson - Birthday,{' '}
                <span className="text-green-600">June 15</span>
              </li>
            </ul>
          </div>
        </aside>
      </div>
    </>

  );
}
